#mongodb configuration
spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform : postgres
    url: jdbc:postgresql://localhost:5432/dofustuff?currentSchema=sch_dofustuff
    username: dofustuff
    password: "DofusStuff01*"
    driverClassName: org.postgresql.Driver
  http:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 100MB
      location: /tmp
#server configuration    
server:
  tomcat:
    basedir: /tmp
endpoints:
  beans:
    sensitive: false
  shutdown:
    enabled: true
  restart:
    enabled: true
management:
  security:
    enabled: false
    
    
    
